[server]
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = true
headless = true
port = 8501
address = "0.0.0.0"

[browser]
gatherUsageStats = false

[theme]
base="light"  # (Optional) Set to "dark" if preferred
